config/routes.rb
#require 'sidekiq/web'

Rails.application.routes.draw do
  apipie

  root 'questions#index'

  namespace :api do
    get :questions, to: "searchs#questions", via: :options
    #put :update, to: "receives#update"
  end

  resources :searchs
  resources :concept_questions, only: [:index]
  resources :concepts, only: [:index]
  resources :questions, only: [:index,:show]
  resources :profiles, only: :index

  #mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_alerts.html.haml
- flash.each do |tag, msg|
  .callout{class: "callout-#{class_for_callout(tag)}"}
    %h4= msg

app/views/shared/_breadcrumb.html.haml
%ol.breadcrumb
  %li Você está em:
  = render_breadcrumbs :tag => :li, :separator => ""

app/views/shared/_content_header.html.haml
%section.content-header
  %h1
    = title
    - if defined? subtitle
      %small= subtitle
  = render 'shared/breadcrumb'

app/views/shared/_header.html.haml
%header.main-header
  / Logo
  %a.logo{:href => root_path}
    / mini logo for sidebar mini 50x50 pixels
    %span.logo-mini
      %b> GER
    / logo for regular state and mobile devices
    %span.logo-lg
      %b> GER
      da
  / Header Navbar: style can be found in header.less
  %nav.navbar.navbar-static-top{:role => "navigation"}
    / Sidebar toggle button
    %a.sidebar-toggle{"data-toggle" => "offcanvas", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-custom-menu
      %ul.nav.navbar-nav
        / Messages: style can be found in dropdown.less
        %li.dropdown.messages-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-envelope-o
            %span.label.label-success= Question.count
          %ul.dropdown-menu
            %li.header You have 4 messages
            %li
              / inner menu: contains the actual data
              %ul.menu
                %li
                  / start message
                  %a{:href => "#"}
                    .pull-left
                      %img.img-circle{:alt => "User Image", :src => image_path('dist/img/user2-160x160.jpg')}/
                    %h4
                      Support Team
                      %small
                        %i.fa.fa-clock-o
                        5 mins
                    %p Why not buy a new awesome theme?
                / end message
            %li.footer
              %a{:href => "#"} See All Messages
        / Notifications: style can be found in dropdown.less
        %li.dropdown.notifications-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-bell-o
            %span.label.label-warning 10
          %ul.dropdown-menu
            %li.header You have 10 notifications
            %li
              / inner menu: contains the actual data
              %ul.menu
                %li
                  %a{:href => "#"}
                    %i.fa.fa-users.text-aqua
                    5 new members joined today
            %li.footer
              %a{:href => "#"} View all
        / Tasks: style can be found in dropdown.less
        %li.dropdown.tasks-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-flag-o
            %span.label.label-danger 9
          %ul.dropdown-menu
            %li.header You have 9 tasks
            %li
              / inner menu: contains the actual data
              %ul.menu
                %li
                  / Task item
                  %a{:href => "#"}
                    %h3
                      Design some buttons
                      %small.pull-right 20%
                    .progress.xs
                      .progress-bar.progress-bar-aqua{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
                        %span.sr-only 20% Complete
                / end task item
            %li.footer
              %a{:href => "#"} View all tasks
        / User Account: style can be found in dropdown.less
        / %li.dropdown.user.user-menu
        /   %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        /     %img.user-image{:alt => "User Image", :src => image_path('user2-160x160.jpg')}/
        /     %span.hidden-xs Alexander Pierce
        /   %ul.dropdown-menu
        /     / User image
        /     %li.user-header
        /       %img.img-circle{:alt => "User Image", :src => image_path('user2-160x160.jpg')}/
        /       %p
        /         Alexander Pierce - Web Developer
        /         %small Member since Nov. 2012
        /     / Menu Body
        /     %li.user-body
        /       .row
        /         .col-xs-4.text-center
        /           %a{:href => "#"} Followers
        /         .col-xs-4.text-center
        /           %a{:href => "#"} Sales
        /         .col-xs-4.text-center
        /           %a{:href => "#"} Friends
        /       / /.row
        /     / Menu Footer
        /     %li.user-footer
        /       .pull-left
        /         %a.btn.btn-default.btn-flat{:href => "#"} Profile
        /       .pull-right
        /         %a.btn.btn-default.btn-flat{:href => "#"} Sign out
        / Control Sidebar Toggle Button
        %li
          %a{"data-toggle" => "control-sidebar", :href => "#"}
            %i.fa.fa-gears
/ ===============================================
/ Left side column. contains the sidebar
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar user panel
    / .user-panel
    /   .pull-left.image
    /     %img.img-circle{:alt => "User Image", :src => image_path('user2-160x160.jpg')}/
    /   .pull-left.info
    /     %p Alexander Pierce
    /     %a{:href => "#"}
    /       %i.fa.fa-circle.text-success
    /       Online
    / search form
    / %form.sidebar-form{:action => "#", :method => "get"}
    /   .input-group
    /     %input.form-control{:name => "q", :placeholder => "Search...", :type => "text"}/
    /     %span.input-group-btn
    /       %button#search-btn.btn.btn-flat{:name => "search", :type => "submit"}
    /         %i.fa.fa-search
    / /.search form
    / sidebar menu: : style can be found in sidebar.less
    %ul.sidebar-menu
      %li.header ACCOUNT NAVIGATION
      %li.treeview.active
        %a{:href => "#"}
          %i.fa.fa-database
          %span
            Mead
          %i.fa.fa-angle-left.pull-right
        %ul.treeview-menu
          %li{class: controller_name == "questions" ? "active" : ""}
            = link_to_with_icon([Question.model_name.human, "fa fa-desktop"], questions_path)
          %li{class: controller_name == "profiles" ? "active" : ""}
            = link_to_with_icon([Profile.model_name.human, "fa fa-keyboard-o"], profiles_path)
          %li{class: controller_name == "concepts" ? "active" : ""}
            = link_to_with_icon([Concept.model_name.human, "fa fa-keyboard-o"], concepts_path)
          %li{class: controller_name == "concept_questions" ? "active" : ""}
            = link_to_with_icon([ConceptQuestion.model_name.human, "fa fa-keyboard-o"], concept_questions_path)
          %li{class: controller_name == "searchs" ? "active" : ""}
            = link_to_with_icon(['Buscas', "fa fa-keyboard-o"], searchs_path)
    / /.sidebar

app/views/shared/_per_page_btn_group.html.haml
Por Páginas:
.btn-group.btn-group-sm{"data-toggle" => "buttons"}
  %label.btn.btn-default{class: (params[:per_page] == "50" ? "active" : "" )}
    = radio_button_tag 'per_page', '50'
    50
  %label.btn.btn-default{class: (params[:per_page] == "100" ? "active" : "" )}
    = radio_button_tag 'per_page', '100'
    100
  %label.btn.btn-default{class: (params[:per_page] == "150" ? "active" : "" )}
    = radio_button_tag 'per_page', '150'
    150
  %label.btn.btn-default{class: (params[:per_page] == "200" ? "active" : "" )}
    = radio_button_tag 'per_page', '200'
    200